# Generated by Django 3.2 on 2021-04-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20210421_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
